import React, { useEffect, useMemo, useState } from "react";
import {
  Alert,
  ScrollView,
  StyleSheet,
  Switch,
  Text,
  TextInput,
  View,
} from "react-native";
import { StatusBar } from "expo-status-bar";
import { SafeAreaView } from "react-native-safe-area-context";
import { useLocalSearchParams, router } from "expo-router";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { Button } from "react-native-paper";
import * as ImagePicker from "expo-image-picker";
import { Image } from "expo-image";

import { ThemedView } from "../../../components/ThemedView";
import { useThemeColor } from "../../../hooks/useThemeColor";
import { Colors } from "../../../constants/Colors";
import categoryApi, { CategoryInput } from "../../../apis/category.api";
import { useCategoryByDocumentId } from "../../../hooks/queries/useCategories";
import { getImageUrl } from "../../../helpers/image";

/**
 * Category Form screen for add/edit in admin panel.
 *
 * Route: /admin/categories/[id]
 *   - id = 'new'          → create mode
 *   - id = <documentId>   → edit mode (pre-fills existing data)
 *
 * Form fields based on Strapi category schema:
 *   - name        (string, required, unique, maxLength 100)
 *   - description (text, optional)
 *   - slug is auto-generated by Strapi from name (uid field); not editable here.
 *
 * Uses React Query mutations for save to DB.
 * Invalidates ["categories"] query on success so the list refreshes.
 */

export default function CategoryFormScreen() {
  const { id } = useLocalSearchParams<{ id: string }>();
  const isEdit = id !== "new";

  const colorScheme =
    useThemeColor({}, "background") === Colors.light.background
      ? "light"
      : "dark";
  const primaryColor = Colors[colorScheme].primary;

  // Form state
  const [formData, setFormData] = useState<CategoryInput>({
    name: "",
    description: "",
    isActive: true,
    image: null,
  });

  // Local state for image preview and upload
  const [selectedImageUri, setSelectedImageUri] = useState<string | null>(null);
  const [isUploadingImage, setIsUploadingImage] = useState(false);

  // Query client for invalidation
  const queryClient = useQueryClient();

  // Load existing category for edit mode
  const { data: categoryData, isLoading: isLoadingCategory } =
    useCategoryByDocumentId(isEdit ? id : "");

  // Pre-fill form when editing
  useEffect(() => {
    if (isEdit && categoryData) {
      setFormData({
        name: categoryData.name || "",
        description: categoryData.description || "",
        isActive: categoryData.isActive ?? true,
        image: categoryData.image?.data?.id || null,
      });

      const imageUrl = getImageUrl(
        categoryData.image?.data?.attributes?.url || ""
      );
      if (imageUrl) {
        setSelectedImageUri(imageUrl);
      }
    }
  }, [categoryData, isEdit]);

  // Create / update mutation
  const mutation = useMutation({
    mutationFn: async (data: CategoryInput) => {
      if (isEdit) {
        return categoryApi.updateCategory(id, data);
      }
      return categoryApi.createCategory(data);
    },
    onSuccess: () => {
      // Invalidate list and single-item cache
      queryClient.invalidateQueries({ queryKey: ["categories"] });
      if (isEdit) {
        queryClient.invalidateQueries({ queryKey: ["category", id] });
      }
      Alert.alert(
        "Success",
        `Category ${isEdit ? "updated" : "created"} successfully.`
      );
      router.back();
    },
    onError: (err) => {
      console.error("Category save error:", err);
      Alert.alert(
        "Error",
        `Failed to ${isEdit ? "update" : "create"} category. Please try again.`
      );
    },
  });

  // Delete mutation
  const deleteMutation = useMutation({
    mutationFn: (documentId: string) => categoryApi.deleteCategory(documentId),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["categories"] });
      Alert.alert("Success", "Category deleted successfully.");
      router.back();
    },
    onError: (err) => {
      console.error("Delete category error:", err);
      Alert.alert("Error", "Failed to delete category. Please try again.");
    },
  });

  const handleDelete = () => {
    Alert.alert(
      "Confirm Delete",
      "Are you sure you want to delete this category? This action cannot be undone.",
      [
        { text: "Cancel", style: "cancel" },
        {
          text: "Delete",
          style: "destructive",
          onPress: () => deleteMutation.mutate(id),
        },
      ]
    );
  };

  const updateField = (
    field: keyof CategoryInput,
    value: string | number | boolean | null
  ) => {
    setFormData((prev) => ({ ...prev, [field]: value }));
  };

  const slugValue = useMemo(() => {
    return formData.name
      .trim()
      .toLowerCase()
      .replace(/\s+/g, "-")
      .replace(/[^a-z0-9-]/g, "");
  }, [formData.name]);

  const handleSubmit = () => {
    if (!formData.name.trim()) {
      Alert.alert("Validation", "Category name is required.");
      return;
    }
    if (formData.name.trim().length > 100) {
      Alert.alert("Validation", "Category name must be 100 characters or less.");
      return;
    }

    // Generate slug: lowercase + replace spaces with hyphen
    const dataToSubmit: CategoryInput = {
      ...formData,
      slug: slugValue,
    };

    mutation.mutate(dataToSubmit);
  };

  const handlePickImage = async () => {
    const permissionResult = await ImagePicker.requestMediaLibraryPermissionsAsync();
    if (!permissionResult.granted) {
      Alert.alert("Permission required", "Allow photo access for image upload.");
      return;
    }

    const result = await ImagePicker.launchImageLibraryAsync({
      mediaTypes: ImagePicker.MediaTypeOptions.Images,
      allowsEditing: true,
      aspect: [1, 1],
      quality: 0.8,
    });

    if (!result.canceled && result.assets[0]) {
      const uri = result.assets[0].uri;
      setSelectedImageUri(uri);

      try {
        setIsUploadingImage(true);

        // Fetch the image file as a Blob from the URI
        const response = await fetch(uri);
        const blob = await response.blob();

        // Create FormData and append the blob as binary content
        const formDataUpload = new FormData();
        formDataUpload.append("files", blob, `category-image-${Date.now()}.jpg`);

        const uploadRes = await categoryApi.uploadImage(formDataUpload);
        const uploadedFileId = uploadRes.data[0].id;
        updateField("image", uploadedFileId);
        Alert.alert("Success", "Image uploaded and ready.");
      } catch (err) {
        console.error("Image upload error:", err);
        Alert.alert("Error", "Failed to upload image. Try again.");
        setSelectedImageUri(null);
      } finally {
        setIsUploadingImage(false);
      }
    }
  };

  if (isLoadingCategory) {
    return (
      <ThemedView style={styles.container}>
        <StatusBar style={colorScheme === "dark" ? "light" : "dark"} />
        <SafeAreaView style={styles.safeArea} edges={["bottom", "left", "right"]}>
          <View style={styles.center}>
            <Text>Loading category...</Text>
          </View>
        </SafeAreaView>
      </ThemedView>
    );
  }

  return (
    <ThemedView style={styles.container}>
      <StatusBar style={colorScheme === "dark" ? "light" : "dark"} />
      {/* SafeAreaView for headered admin screen (excludes top – handled by Stack header) */}
      <SafeAreaView style={styles.safeArea} edges={["bottom", "left", "right"]}>
        <ScrollView contentContainerStyle={styles.scrollContent}>
          <Text style={[styles.title, { color: primaryColor }]}>
            {isEdit ? "Edit Category" : "Add New Category"}
          </Text>

          <View style={styles.form}>
            {/* Name – required, unique */}
            <Text style={styles.label}>
              Category Name <Text style={styles.required}>*</Text>
            </Text>
            <TextInput
              style={styles.input}
              placeholder="e.g. Bulb, Wire, Switches"
              value={formData.name}
              onChangeText={(text) => updateField("name", text)}
              maxLength={100}
              autoCapitalize="words"
            />
            <Text style={styles.hint}>Required · Unique · Max 100 characters</Text>

            {/* Description – optional */}
            <Text style={styles.label}>Description</Text>
            <TextInput
              style={[styles.input, styles.multiline]}
              placeholder="Short description of this category (optional)"
              value={formData.description}
              onChangeText={(text) => updateField("description", text)}
              multiline
              numberOfLines={4}
              textAlignVertical="top"
            />

            <View style={styles.switchRow}>
              <Text>Active Category</Text>
              <Switch
                value={formData.isActive}
                onValueChange={(value) => updateField("isActive", value)}
              />
            </View>

            {/* Category image upload */}
            <Text style={styles.label}>Category Image</Text>
            <View style={styles.imagePreviewContainer}>
              {selectedImageUri ? (
                <Image
                  source={{ uri: selectedImageUri }}
                  style={styles.imagePreview}
                  contentFit="cover"
                />
              ) : (
                <Text style={styles.noImageText}>No image selected</Text>
              )}
              <Button
                mode="outlined"
                onPress={handlePickImage}
                disabled={isUploadingImage}
                style={styles.pickButton}
              >
                {isUploadingImage ? "Uploading..." : "Pick & Upload Image"}
              </Button>
            </View>
            <Text style={styles.note}>
              {isEdit
                ? "Current image shown above; pick new to replace."
                : "Optional image upload for category display."}
            </Text>

            {/* Slug preview */}
            <Text style={styles.label}>Slug (auto)</Text>
            <View style={styles.slugBox}>
              <Text style={styles.slugText}>{slugValue || "-"}</Text>
            </View>
            <Text style={styles.note}>
              Slug is generated from the name using lowercase and hyphens.
            </Text>
          </View>

          <Button
            mode="contained"
            buttonColor={primaryColor}
            onPress={handleSubmit}
            loading={mutation.isPending || isUploadingImage}
            disabled={mutation.isPending || isUploadingImage}
            style={styles.submitButton}
          >
            {isEdit ? "Update Category" : "Create Category"}
          </Button>

          {isEdit && (
            <Button
              mode="outlined"
              textColor="red"
              onPress={handleDelete}
              style={styles.deleteButton}
              disabled={deleteMutation.isPending || mutation.isPending}
            >
              Delete Category
            </Button>
          )}

          <Button
            mode="outlined"
            onPress={() => router.back()}
            style={styles.cancelButton}
            disabled={mutation.isPending}
          >
            Cancel
          </Button>
        </ScrollView>
      </SafeAreaView>
    </ThemedView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  safeArea: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    padding: 24,
  },
  title: {
    fontSize: 26,
    fontWeight: "bold",
    marginBottom: 28,
    textAlign: "center",
  },
  form: {
    width: "100%",
    maxWidth: 480,
    alignSelf: "center",
  },
  label: {
    fontSize: 14,
    fontWeight: "600",
    marginBottom: 6,
    marginTop: 4,
  },
  required: {
    color: "red",
  },
  input: {
    borderWidth: 1,
    borderColor: "#ddd",
    borderRadius: 8,
    padding: 12,
    marginBottom: 4,
    backgroundColor: "#fff",
    fontSize: 15,
  },
  multiline: {
    minHeight: 100,
    textAlignVertical: "top",
  },
  switchRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  hint: {
    fontSize: 11,
    opacity: 0.5,
    marginBottom: 16,
    marginLeft: 2,
  },
  note: {
    fontSize: 13,
    opacity: 0.6,
    fontStyle: "italic",
    marginTop: 8,
    marginBottom: 24,
    lineHeight: 18,
  },
  imagePreviewContainer: {
    alignItems: "center",
    marginBottom: 16,
  },
  imagePreview: {
    width: 140,
    height: 140,
    borderRadius: 12,
    marginBottom: 8,
    backgroundColor: "#f0f0f0",
  },
  noImageText: {
    fontSize: 14,
    opacity: 0.5,
    marginBottom: 8,
  },
  pickButton: {
    marginTop: 6,
  },
  slugBox: {
    borderWidth: 1,
    borderColor: "#ddd",
    borderRadius: 8,
    padding: 12,
    backgroundColor: "#f9f9f9",
  },
  slugText: {
    fontSize: 13,
    fontFamily: "monospace",
    color: "#444",
  },
  submitButton: {
    marginTop: 8,
    padding: 4,
    maxWidth: 480,
    alignSelf: "center",
    width: "100%",
  },
  deleteButton: {
    marginTop: 16,
    padding: 4,
    maxWidth: 480,
    alignSelf: "center",
    width: "100%",
    borderColor: "red",
  },
  cancelButton: {
    marginTop: 10,
    maxWidth: 480,
    alignSelf: "center",
    width: "100%",
  },
  center: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 16,
  },
});
